In [7]:
import pandas as pd

In [8]:
import os
os.getcwd(), os.listdir()

('C:\\Users\\pc\\Desktop\\Reinforcement\\Supervised ML Algoithms\\ML PROJECTS',
 ['.ipynb_checkpoints',
  'CPIAUCSL.csv',
  'Metro_median_sale_price_uc_sfrcondo_week.csv',
  'Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_month.csv',
  'MORTGAGE30US.csv',
  'RRVRUSQ156N.csv',
  'Untitled.ipynb'])

In [10]:
fed_files = ["MORTGAGE30US.csv", "RRVRUSQ156N.csv", "CPIAUCSL.csv"]
dfs = [pd.read_csv (f,parse_dates=True, index_col=0) for f in fed_files]

In [11]:
dfs[0]

            MORTGAGE30US
DATE
1971-04-02          7.33
1971-04-09          7.31
1971-04-16          7.31
1971-04-23          7.31
1971-04-30          7.29
...                  ...
2022-07-14          5.51
2022-07-21          5.54
2022-07-28          5.30
2022-08-04          4.99
2022-08-11          5.22

[2681 rows x 1 columns]

In [13]:
dfs[1]

            RRVRUSQ156N
DATE
1956-01-01          6.2
1956-04-01          5.9
1956-07-01          6.3
1956-10-01          5.8
1957-01-01          5.3
...                 ...
2021-04-01          6.2
2021-07-01          5.8
2021-10-01          5.6
2022-01-01          5.8
2022-04-01          5.6

[266 rows x 1 columns]

In [14]:
dfs[2]

            CPIAUCSL
DATE
1947-01-01    21.480
1947-02-01    21.620
1947-03-01    22.000
1947-04-01    22.000
1947-05-01    21.950
...              ...
2022-03-01   287.708
2022-04-01   288.663
2022-05-01   291.474
2022-06-01   295.328
2022-07-01   295.271

[907 rows x 1 columns]

In [16]:
fed_data =pd.concat(dfs, axis=1, sort=False)

In [18]:
fed_data

            MORTGAGE30US  RRVRUSQ156N  CPIAUCSL
DATE
1971-04-02          7.33          NaN       NaN
1971-04-09          7.31          NaN       NaN
1971-04-16          7.31          NaN       NaN
1971-04-23          7.31          NaN       NaN
1971-04-30          7.29          NaN       NaN
...                  ...          ...       ...
2022-02-01           NaN          NaN   284.182
2022-03-01           NaN          NaN   287.708
2022-05-01           NaN          NaN   291.474
2022-06-01           NaN          NaN   295.328
2022-07-01           NaN          NaN   295.271

[3507 rows x 3 columns]

In [21]:
fed_data=fed_data.ffill()

In [23]:
fed_data.tail(50)

            MORTGAGE30US  RRVRUSQ156N  CPIAUCSL
DATE
2015-08-01          5.22          5.6   238.033
2015-09-01          5.22          5.6   237.498
2015-11-01          5.22          5.6   238.017
2015-12-01          5.22          5.6   237.761
2016-02-01          5.22          5.6   237.336
2016-03-01          5.22          5.6   238.080
2016-05-01          5.22          5.6   239.557
2016-06-01          5.22          5.6   240.222
2016-08-01          5.22          5.6   240.545
2016-11-01          5.22          5.6   242.026
2017-02-01          5.22          5.6   244.006
2017-03-01          5.22          5.6   243.892
2017-05-01          5.22          5.6   244.004
2017-08-01          5.22          5.6   245.183
2017-09-01          5.22          5.6   246.435
2017-11-01          5.22          5.6   247.284
2017-12-01          5.22          5.6   247.805
2018-05-01          5.22          5.6   250.779
2018-06-01          5.22          5.6   251.118
2018-08-01          5.22          5.6   251.749
2018-09-01          5.22          5.6   252.239
2018-12-01          5.22          5.6   252.551
2019-02-01          5.22          5.6   253.135
2019-03-01          5.22          5.6   254.273
2019-05-01          5.22          5.6   255.325
2019-06-01          5.22          5.6   255.361
2019-09-01          5.22          5.6   256.596
2019-11-01          5.22          5.6   257.788
2019-12-01          5.22          5.6   258.263
2020-02-01          5.22          5.6   259.007
2020-03-01          5.22          5.6   258.165
2020-05-01          5.22          5.6   255.944
2020-06-01          5.22          5.6   257.217
2020-08-01          5.22          5.6   259.580
2020-09-01          5.22          5.6   260.190
2020-11-01          5.22          5.6   260.721
2020-12-01          5.22          5.6   261.564
2021-02-01          5.22          5.6   263.346
2021-03-01          5.22          5.6   265.028
2021-05-01          5.22          5.6   268.599
2021-06-01          5.22          5.6   270.955
2021-08-01          5.22          5.6   273.092
2021-09-01          5.22          5.6   274.214
2021-11-01          5.22          5.6   278.524
2021-12-01          5.22          5.6   280.126
2022-02-01          5.22          5.6   284.182
2022-03-01          5.22          5.6   287.708
2022-05-01          5.22          5.6   291.474
2022-06-01          5.22          5.6   295.328
2022-07-01          5.22          5.6   295.271

In [25]:
zillow_files = ["Metro_median_sale_price_uc_sfrcondo_week.csv","Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_month.csv"]
dfs=[pd.read_csv(f) for f in zillow_files]

In [46]:
dfs = [pd.DataFrame(df.iloc[0,5:]) for df in dfs]
for df in dfs:
    df.index = pd.to_datetime(df.index)
    df["month"] = df.index.to_period("M")

ValueError: time data "month" doesn't match format "%Y-%m-%d". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [31]:
dfs[0]

,2008-02-02,2008-02-09,2008-02-16,2008-02-23,2008-03-01,2008-03-08,2008-03-15,2008-03-22,2008-03-29,2008-04-05,...,2022-05-07,2022-05-14,2022-05-21,2022-05-28,2022-06-04,2022-06-11,2022-06-18,2022-06-25,2022-07-02,2022-07-09
0,190000.0,190000.0,193000.0,189900.0,194900.0,190000.0,195000.0,198500.0,199000.0,195000.0,...,369900.0,370000.0,370000.0,375000.0,375000.0,370000.0,375000.0,370000.0,370000.0,362500.0
1,400000.0,418250.0,420000.0,420000.0,400000.0,407000.0,410000.0,415117.0,410000.0,406500.0,...,550000.0,555000.0,550000.0,575000.0,575000.0,578000.0,590000.0,582000.0,585000.0,595000.0
2,497500.0,515000.0,520000.0,525000.0,498250.0,503750.0,512000.0,489000.0,500000.0,500000.0,...,914000.0,925000.0,925000.0,951000.0,950000.0,920500.0,925000.0,900000.0,900500.0,906000.0
3,245000.0,245000.0,251000.0,255000.0,255000.0,245000.0,245000.0,250000.0,251875.0,267000.0,...,315000.0,310000.0,315500.0,315000.0,330000.0,324950.0,335000.0,325000.0,325000.0,315000.0
4,144250.0,148900.0,139000.0,143700.0,145900.0,154600.0,150000.0,149995.0,155900.0,156900.0,...,422000.0,430000.0,430000.0,425000.0,440000.0,425000.0,427750.0,426000.0,420000.0,420000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,NaN,170000.0,182400.0,170000.0,170000.0,175000.0,175000.0,184200.0,185000.0,175000.0,...,340500.0,345000.0,327700.0,345000.0,350000.0,343250.0,359900.0,352000.0,336000.0,342990.0
80,138000.0,160000.0,150000.0,151750.0,154500.0,154750.0,155500.0,138700.0,154750.0,146000.0,...,270000.0,285250.0,295000.0,273450.0,301000.0,290000.0,300900.0,281900.0,289250.0,280000.0
81,NaN,206000.0,215500.0,210000.0,210000.0,199950.0,211500.0,233500.0,220000.0,228500.0,...,527000.0,540000.0,535000.0,552500.0,543750.0,571000.0,530300.0,569900.0,539950.0,572500.0
82,210000.0,170000.0,170500.0,197500.0,180000.0,202500.0,197250.0,218500.0,205000.0,212500.0,...,456000.0,450000.0,428500.0,480000.0,465000.0,440000.0,450250.0,416000.0,465000.0,435250.0
83,NaN,255000.0,205000.0,229900.0,235000.0,257728.0,201000.0,227250.0,223450.0,235000.0,...,575000.0,585250.0,575000.0,550000.0,569900.0,560000.0,595000.0,550000.0,556058.0,595000.0

In [36]:

for i, df in enumerate(dfs):
    df.index = pd.to_datetime(df.index)
    df["month"] = df.index.to_period("M")
    dfs[i] = df  # save back the modified df


dfs_agg = [df.groupby("month").mean() for df in dfs]


price_data = pd.merge(dfs_agg[0], dfs_agg[1], left_index=True, right_index=True, how="outer")


price_data = price_data.sort_index()

In [39]:
del price_data["month"]
price_data.column = ["price", "value"]
price_data

KeyError: 'month'

In [41]:

fed_data = fed_data.dropna()
fed_data.tail(20)

            MORTGAGE30US  RRVRUSQ156N  CPIAUCSL
DATE
2020-03-01          5.22          5.6   258.165
2020-05-01          5.22          5.6   255.944
2020-06-01          5.22          5.6   257.217
2020-08-01          5.22          5.6   259.580
2020-09-01          5.22          5.6   260.190
2020-11-01          5.22          5.6   260.721
2020-12-01          5.22          5.6   261.564
2021-02-01          5.22          5.6   263.346
2021-03-01          5.22          5.6   265.028
2021-05-01          5.22          5.6   268.599
2021-06-01          5.22          5.6   270.955
2021-08-01          5.22          5.6   273.092
2021-09-01          5.22          5.6   274.214
2021-11-01          5.22          5.6   278.524
2021-12-01          5.22          5.6   280.126
2022-02-01          5.22          5.6   284.182
2022-03-01          5.22          5.6   287.708
2022-05-01          5.22          5.6   291.474
2022-06-01          5.22          5.6   295.328
2022-07-01          5.22          5.6   295.271

In [42]:
from datetime import timedelta
fed_data.index = fed_data.index + timedelta(days=2)

In [44]:
price_data =  fed_data.merge(price_data, left_index=True, right_index=True)

In [45]:
price_data.columns =["interest","vacancy", "cpi", "price","value"]
price_data

ValueError: Length mismatch: Expected axis has 1076 elements, new values have 5 elements

In [ ]:
price_data.plot.line(y="price", use_index=True)